const CONFIG = {
  poster: "images/seq_arch/est_00.jpg",

  timeline: [
    {
      id: "aereo",
      label: "Panorâmica",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9c3-2 6-3 9-3s6 1 9 3"/><path d="M3 15c3 2 6 3 9 3s6-1 9-3"/><circle cx="12" cy="12" r="3"/></svg>`,
    },
    {
      id: "pool",
      label: "Estacionamento",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 17V7h4a3 3 0 0 1 0 6H9"/></svg>`,
    },
    {
      id: "jardim",
      label: "Prédio",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="1"/><path d="M9 22V12h6v10"/><path d="M8 6h1M11 6h1M14 6h1M8 10h1M11 10h1M14 10h1"/></svg>`,
    },
    {
      id: "living",
      label: "Hall",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21V7l9-4 9 4v14"/><path d="M13 21v-6h-2v6"/><path d="M3 10h18"/></svg>`,
    },
    {
      id: "kitchen",
      label: "Parque",
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22V12"/><circle cx="12" cy="7" r="5"/><path d="M5 22h14"/></svg>`,
    },
  ],

  scenes: {
    aereo: { video: "images/dia_low.webm", pois: [] },
    pool: { video: "images/estacionamento.webm", pois: [] },
    living: { video: "images/hall.webm", pois: [] },
    jardim: { video: "images/predio.webm", pois: [] },
    kitchen: { video: "images/parque.webm", pois: [] },
  },

  sequences: {
    "aereo-to-pool": {
      folder: "images/seq_arch/",
      prefix: "est_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      fps: 30,
    },
    "pool-to-aereo": {
      folder: "images/seq_arch/",
      prefix: "est_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "pool-to-living": {
      folder: "images/seq_arch/",
      prefix: "est_to_portaria_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "living-to-pool": {
      folder: "images/seq_arch/",
      prefix: "est_to_portaria_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "pool-to-kitchen": {
      folder: "images/seq_arch/",
      prefix: "est_to_parque_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "kitchen-to-pool": {
      folder: "images/seq_arch/",
      prefix: "est_to_parque_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "pool-to-jardim": {
      folder: "images/seq_arch/",
      prefix: "est_to_predio_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "jardim-to-pool": {
      folder: "images/seq_arch/",
      prefix: "est_to_predio_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "aereo-to-jardim": {
      folder: "images/seq_arch/",
      prefix: "arch_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "jardim-to-aereo": {
      folder: "images/seq_arch/",
      prefix: "arch_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "aereo-to-kitchen": {
      folder: "images/seq_arch/",
      prefix: "parque_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "kitchen-to-aereo": {
      folder: "images/seq_arch/",
      prefix: "parque_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "aereo-to-living": {
      folder: "images/seq/",
      prefix: "pano_to_hall_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "living-to-aereo": {
      folder: "images/seq/",
      prefix: "pano_to_hall_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "living-to-kitchen": {
      folder: "images/seq_arch/",
      prefix: "portaria_to_parque_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "kitchen-to-living": {
      folder: "images/seq_arch/",
      prefix: "portaria_to_parque_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "jardim-to-kitchen": {
      folder: "images/seq/",
      prefix: "predio_to_parque_",
      from: 0,
      to: 46,
      pad: 2,
      ext: "jpg",
    },
    "kitchen-to-jardim": {
      folder: "images/seq/",
      prefix: "predio_to_parque_",
      from: 0,
      to: 46,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
    "jardim-to-living": {
      folder: "images/seq_arch/",
      prefix: "torre_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
    },
    "living-to-jardim": {
      folder: "images/seq_arch/",
      prefix: "torre_",
      from: 0,
      to: 47,
      pad: 2,
      ext: "jpg",
      reverse: true,
    },
  },

  transitions: {
    aereo: {
      pool: "aereo-to-pool",
      jardim: "aereo-to-jardim",
      kitchen: "aereo-to-kitchen",
      living: "aereo-to-living",
    },
    pool: {
      aereo: "pool-to-aereo",
      living: "pool-to-living",
      kitchen: "pool-to-kitchen",
      jardim: "pool-to-jardim",
    },
    living: {
      pool: "living-to-pool",
      jardim: "living-to-jardim",
      kitchen: "living-to-kitchen",
      aereo: "living-to-aereo",
    },
    kitchen: {
      pool: "kitchen-to-pool",
      jardim: "kitchen-to-jardim",
      living: "kitchen-to-living",
      aereo: "kitchen-to-aereo",
    },
    jardim: { pool: "jardim-to-pool", aereo: "jardim-to-aereo", living: "jardim-to-living", kitchen: "jardim-to-kitchen" },
  },
};
